server.port=${DOTAPEDIA_SERVER_PORT}

spring.datasource.url=jdbc:postgresql://${DOTAPEDIA_DATASOURCE_HOST}/${DOTAPEDIA_DATASOURCE_DBNAME}
spring.datasource.username=${DOTAPEDIA_DATASOURCE_USER}
spring.datasource.password=${DOTAPEDIA_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# show sql
# spring.jpa.properties.hibernate.show_sql=true
# spring.jpa.properties.hibernate.use_sql_comments=true
# spring.jpa.properties.hibernate.format_sql=true

# logging level
logging.level.root=ERROR
logging.level.wiwitaditya.demo.dotapedia=DEBUG

# news api
dotapedia.newsapi.scheme=https
dotapedia.newsapi.host=newsapi.org
dotapedia.newsapi.path=v2/top-headlines
dotapedia.newsapi.apikey=${NEWSAPI_APIKEY}
## update-interfall is in minute
dotapedia.newsapi.updateinterval=10
